import Teams from "./teams";
import Fixture from "./fixture";

const {
    Manchester_United,
    Manchester_city,
    Leicester_city,
    Liverpool,
    Watford,
    West_ham,
    Wolvershampton,
    Bournemouth,
    Brighton,
    Burnley,
    Chelsea,
    Crystal_palace,
    Norwich_city,
    Arsenal,
    Aston_villa,
    Sheffield_united,
    Southampton,
    Newcastle_united,
    Everton,
    Tottenham
} = Teams;
export default [
    [
        new Fixture(Liverpool, Norwich_city),
        new Fixture(West_ham, Manchester_city),
        new Fixture(Crystal_palace, Everton),
        new Fixture(Burnley, Southampton),
        new Fixture(Watford, Brighton),
        new Fixture(Bournemouth, Sheffield_united),
        new Fixture(Tottenham, Aston_villa),
        new Fixture(Leicester_city, Wolvershampton),
        new Fixture(Newcastle_united, Arsenal),
        new Fixture(Manchester_United, Chelsea)
    ],
    [
        new Fixture(Arsenal, Burnley),
        new Fixture(Southampton, Liverpool),
        new Fixture(Brighton, West_ham),
        new Fixture(Everton, Watford),
        new Fixture(Norwich_city, Newcastle_united),
        new Fixture(Aston_villa, Bournemouth),
        new Fixture(Manchester_city, Tottenham),
        new Fixture(Sheffield_united, Crystal_palace),
        new Fixture(Chelsea, Leicester_city),
        new Fixture(Wolvershampton, Manchester_United)
    ],
    [
        new Fixture(Aston_villa, Everton),
        new Fixture(Norwich_city, Chelsea),
        new Fixture(Brighton, Southampton),
        new Fixture(Manchester_United, Crystal_palace),
        new Fixture(Watford, West_ham),
        new Fixture(Sheffield_united, Leicester_city),
        new Fixture(Liverpool, Arsenal),
        new Fixture(Bournemouth, Manchester_city),
        new Fixture(Tottenham, Newcastle_united),
        new Fixture(Wolvershampton, Burnley)
    ],
    [
        new Fixture(Southampton, Manchester_United),
        new Fixture(Crystal_palace, Aston_villa),
        new Fixture(Chelsea, Sheffield_united),
        new Fixture(Newcastle_united, Watford),
        new Fixture(Manchester_city, Brighton),
        new Fixture(West_ham, Norwich_city),
        new Fixture(Leicester_city, Bournemouth),
        new Fixture(Burnley, Liverpool),
        new Fixture(Everton, Wolvershampton),
        new Fixture(Arsenal, Tottenham)
    ],
    [
        new Fixture(Liverpool, Newcastle_united),
        new Fixture(Manchester_United, Leicester_city),
        new Fixture(Sheffield_united, Southampton),
        new Fixture(Brighton, Burnley),
        new Fixture(Wolvershampton, Chelsea),
        new Fixture(Tottenham, Crystal_palace),
        new Fixture(Norwich_city, Manchester_city),
        new Fixture(Bournemouth, Everton),
        new Fixture(Watford, Arsenal),
        new Fixture(Aston_villa, West_ham)
    ],
    [
        new Fixture(Southampton, Bournemouth),
        new Fixture(Leicester_city, Tottenham),
        new Fixture(Burnley, Norwich_city),
        new Fixture(Everton, Sheffield_united),
        new Fixture(Manchester_city, Watford),
        new Fixture(Newcastle_united, Brighton),
        new Fixture(West_ham, Manchester_United),
        new Fixture(Crystal_palace, Wolvershampton),
        new Fixture(Arsenal, Aston_villa),
        new Fixture(Chelsea, Liverpool)
    ],
    [
        new Fixture(Sheffield_united, Liverpool),
        new Fixture(Crystal_palace, Norwich_city),
        new Fixture(Aston_villa, Burnley),
        new Fixture(Bournemouth, West_ham),
        new Fixture(Tottenham, Southampton),
        new Fixture(Chelsea, Brighton),
        new Fixture(Everton, Manchester_city),
        new Fixture(Leicester_city, Newcastle_united),
        new Fixture(Manchester_United, Arsenal),
        new Fixture(Wolves, Watford)
    ],
    [
        new Fixture(Brighton, Tottenham),
        new Fixture(Norwich_city, Aston_villa),
        new Fixture(Watford, Sheffield_united),
        new Fixture(Burnley, Everton),
        new Fixture(Liverpool, Leicester_city),
        new Fixture(West_ham, Crystal_palace),
        new Fixture(Southampton, Chelsea),
        new Fixture(Manchester_city, Wolvershampton),
        new Fixture(Arsenal, Bournemouth),
        new Fixture(Newcastle_united, Manchester_United)
    ],
    [
        new Fixture(Everton, West_ham),
        new Fixture(Aston_villa, Brighton),
        new Fixture(Tottenham, Watford),
        new Fixture(Wolvershampton, Southampton),
        new Fixture(Chelsea, Newcastle_united),
        new Fixture(Bournemouth, Norwich_city),
        new Fixture(Leicester_city, Burnley),
        new Fixture(Crystal_palace, Manchester_city),
        new Fixture(Manchester_United, Liverpool),
        new Fixture(Sheffield_united, Arsenal)
    ],
    [
        new Fixture(Southampton, Leicester_city),
        new Fixture(Manchester_city, Aston_villa),
        new Fixture(Watford, Bournemouth),
        new Fixture(Brighton, Everton),
        new Fixture(West_ham, Sheffield_united),
        new Fixture(Burnley, Chelsea),
        new Fixture(Newcastle_united, Wolvershampton),
        new Fixture(Arsenal, Crystal_palace),
        new Fixture(Liverpool, Tottenham),
        new Fixture(Norwich_city, Manchester_United)
    ],
    [
        new Fixture(Bournemouth, Manchester_United),
        new Fixture(West_ham, Newcastle_united),
        new Fixture(Aston_villa, Liverpool),
        new Fixture(Arsenal, Wolvershampton),
        new Fixture(Sheffield_united, Burnley),
        new Fixture(Brighton, Norwich_city),
        new Fixture(Manchester_city, Southampton),
        new Fixture(Watford, Chelsea),
        new Fixture(Crystal_palace, Leicester_city),
        new Fixture(Everton, Tottenham)
    ],
    [
        new Fixture(Norwich_city, Watford),
        new Fixture(Chelsea, Crystal_palace),
        new Fixture(Burnley, West_ham),
        new Fixture(Newcastle_united, Bournemouth),
        new Fixture(Southampton, Everton),
        new Fixture(Tottenham, Sheffield_united),
        new Fixture(Leicester_city, Arsenal),
        new Fixture(Wolvershampton, Aston_villa),
        new Fixture(Manchester_United, Brighton),
        new Fixture(Liverpool, Manchester_city)
    ],
    [
        new Fixture(West_ham, Tottenham),
        new Fixture(Arsenal, Southampton),
        new Fixture(Brighton, Leicester_city),
        new Fixture(Watford, Burnley),
        new Fixture(Crystal_palace, Liverpool),
        new Fixture(Bournemouth, Wolvershampton),
        new Fixture(Everton, Norwich_city),
        new Fixture(Manchester_city, Chelsea),
        new Fixture(Sheffield_united, Manchester_United),
        new Fixture(Aston_villa, Newcastle_united)
    ],
    [
        new Fixture(Newcastle_united, Manchester_city),
        new Fixture(Liverpool, Brighton),
        new Fixture(Chelsea, West_ham),
        new Fixture(Tottenham, Bournemouth),
        new Fixture(Southampton, Watford),
        new Fixture(Norwich_city, Arsenal),
        new Fixture(Wolvershampton, Sheffield_united),
        new Fixture(Leicester_city, Everton),
        new Fixture(Manchester_United, Aston_villa),
        new Fixture(Burnley, Crystal_palace)
    ],
    [
        new Fixture(Crystal_palace, Bournemouth),
        new Fixture(Burnley, Manchester_city),
        new Fixture(Chelsea, Aston_villa),
        new Fixture(Leicester_city, Watford),
        new Fixture(Southampton, Norwich_city),
        new Fixture(Wolvershampton, West_ham),
        new Fixture(Manchester_United, Tottenham),
        new Fixture(Liverpool, Everton),
        new Fixture(Sheffield_united, Newcastle_united),
        new Fixture(Arsenal, Brighton)
    ],
    [
        new Fixture(Everton, Chelsea),
        new Fixture(Bournemouth, Liverpool),
        new Fixture(Tottenham, Burnley),
        new Fixture(Watford, Crystal_palace),
        new Fixture(Manchester_city, Manchester_United),
        new Fixture(Aston_villa, Leicester_city),
        new Fixture(Newcastle_united, Southampton),
        new Fixture(Norwich_city, Sheffield_united),
        new Fixture(Brighton, Wolvershampton),
        new Fixture(West_ham, Arsenal)
    ],
    [
        new Fixture(Liverpool, Watford),
        new Fixture(Chelsea, Bournemouth),
        new Fixture(Sheffield_united, Aston_villa),
        new Fixture(Leicester_city, Norwich_city),
        new Fixture(Burnley, Newcastle_united),
        new Fixture(Southampton, West_ham),
        new Fixture(Manchester_United, Everton),
        new Fixture(Wolvershampton, Tottenham),
        new Fixture(Arsenal, Manchester_city),
        new Fixture(Crystal_palace, Brighton)
    ],
    [
        new Fixture(West_ham, Liverpool),
        new Fixture(Everton, Arsenal),
        new Fixture(Newcastle_united, Crystal_palace),
        new Fixture(Aston_villa, Southampton),
        new Fixture(Norwich_city, Wolvershampton),
        new Fixture(Brighton, Sheffield_united),
        new Fixture(Bournemouth, Burnley),
        new Fixture(Manchester_city, Leicester_city),
        new Fixture(Watford, Manchester_United),
        new Fixture(Tottenham, Chelsea)
    ],
    [
        new Fixture(Tottenham, Brighton),
        new Fixture(Bournemouth, Arsenal),
        new Fixture(Sheffield_united, Watford),
        new Fixture(Chelsea, Southampton),
        new Fixture(Aston_villa, Norwich_city),
        new Fixture(Crystal_palace, West_ham),
        new Fixture(Everton, Burnley),
        new Fixture(Manchester_United, Newcastle_united),
        new Fixture(Leicester_city, Liverpool),
        new Fixture(Wolvershampton, Manchester_city)
    ],
    [
        new Fixture(Brighton, Bournemouth),
        new Fixture(Southampton, Crystal_palace),
        new Fixture(Newcastle_united, Everton),
        new Fixture(Watford, Aston_villa),
        new Fixture(Norwich_city, Tottenham),
        new Fixture(West_ham, Leicester_city),
        new Fixture(Burnley, Manchester_United),
        new Fixture(Arsenal, Chelsea),
        new Fixture(Liverpool, Wolvershampton),
        new Fixture(Manchester_city, Sheffield_united)
    ],
    [
        new Fixture(Brighton, Chelsea),
        new Fixture(Burnley, Aston_villa),
        new Fixture(Newcastle_united, Leicester_city),
        new Fixture(Watford, Wolvershampton),
        new Fixture(Southampton, Tottenham),
        new Fixture(West_ham, Bournemouth),
        new Fixture(Manchester_city, Everton),
        new Fixture(Norwich_city, Crystal_palace),
        new Fixture(Arsenal, Manchester_United),
        new Fixture(Liverpool, Sheffield_united)
    ],
    [
        new Fixture(Sheffield_united, West_ham),
        new Fixture(Crystal_palace, Arsenal),
        new Fixture(Everton, Brighton),
        new Fixture(Leicester_city, Southampton),
        new Fixture(Manchester_United, Norwich_city),
        new Fixture(Chelsea, Burnley),
        new Fixture(Wolvershampton, Newcastle_united),
        new Fixture(Tottenham, Liverpool),
        new Fixture(Bournemouth, Watford),
        new Fixture(Aston_villa, Manchester_city)
    ],
    [
        new Fixture(Watfor, Tottenham),
        new Fixture(Brighton, Aston_villa),
        new Fixture(Manchester_city, Crystal_palace),
        new Fixture(West_ham, Everton),
        new Fixture(Arsenal, Sheffield_united),
        new Fixture(Norwich_city, Bournemouth),
        new Fixture(Southampton, Wolvershampton),
        new Fixture(Newcastle_united, Chelsea),
        new Fixture(Burnley, Leicester_city),
        new Fixture(Liverpool, Manchester_United)
    ],
    [
        new Fixture(Bournemouth, Brighton),
        new Fixture(Aston_villa, Watford),
        new Fixture(Crystal_palace, Southampton),
        new Fixture(Sheffield_united, Manchester_city),
        new Fixture(Everton, Newcastle_united),
        new Fixture(Chelsea, Arsenal),
        new Fixture(Leicester_city, West_ham),
        new Fixture(Tottenham, Norwich_city),
        new Fixture(Manchester_United, Burnley),
        new Fixture(Wolvershampton, Liverpool)
    ],
    [
        new Fixture(Tottenham, Manchester_city),
        new Fixture(Burnley, Arsenal),
        new Fixture(Newcastle_united, Norwich_city),
        new Fixture(Manchester_United, Wolvershampton),
        new Fixture(Crystal_palace, Sheffield_united),
        new Fixture(West_ham, Brighton),
        new Fixture(Leicester_city, Chelsea),
        new Fixture(Bournemouth, Aston_villa),
        new Fixture(Watford, Everton),
        new Fixture(Liverpool, Southampton)
    ],
    [
        new Fixture(Aston_villa, Tottenham),
        new Fixture(Brighton, Watford),
        new Fixture(Southampton, Burnley),
        new Fixture(Everton, Crystal_palace),
        new Fixture(Norwich_city, Liverpool),
        new Fixture(Wolvershampton, Leicester_city),
        new Fixture(Chelsea, Manchester_United),
        new Fixture(Manchester_city, West_ham),
        new Fixture(Arsenal, Newcastle_united),
        new Fixture(Sheffield_united, Bournemouth)
    ],
    [
        new Fixture(Crystal_palace, Newcastle_united),
        new Fixture(Arsenal, Everton),
        new Fixture(Burnley, Bournemouth),
        new Fixture(Leicester_city, Manchester_city),
        new Fixture(Sheffield_united, Brighton),
        new Fixture(Wolvershampton, Norwich_city),
        new Fixture(Liverpool, West_ham),
        new Fixture(Southampton, Aston_villa),
        new Fixture(Manchester_United, Watford),
        new Fixture(Chelsea, Tottenham)
    ],
    [
        new Fixture(Bournemouth, Chelsea),
        new Fixture(Newcastle_united, Burnley),
        new Fixture(Norwich_city, Liverpool),
        new Fixture(West_ham, Southampton),
        new Fixture(Brighton, Crystal_palace),
        new Fixture(Everton, Manchester_United),
        new Fixture(Tottenham, Wolvershampton),
        new Fixture(Aston_villa, Sheffield_united),
        new Fixture(Manchester_city, Arsenal),
        new Fixture(Watford, Liverpool)
    ],
    [
        new Fixture(Wolvershampton, Brighton),
        new Fixture(Burnley, Tottenham),
        new Fixture(Arsenal, Tottenham),
        new Fixture(Leicester_city, Aston_villa),
        new Fixture(Southampton, Newcastle_united),
        new Fixture(Liverpool, Bournemouth),
        new Fixture(Sheffield_united, Norwich_city),
        new Fixture(Crystal_palace, Watford),
        new Fixture(Chelsea, Everton),
        new Fixture(Manchester_United, Manchester_city)
    ],
    [
        new Fixture(West_ham, Wolvershampton),
        new Fixture(Brighton, Arsenal),
        new Fixture(Tottenham, Manchester_United),
        new Fixture(Everton, Liverpool),
        new Fixture(Norwich_city, Southampton),
        new Fixture(Newcastle_united, Sheffield_united),
        new Fixture(Watford, Leicester_city),
        new Fixture(Manchester_city, Burnley),
        new Fixture(Aston_villa, Chelsea),
        new Fixture(Bournemouth, Crystal_palace)
    ],
    [
        new Fixture(Norwich_city, Everton),
        new Fixture(Leicester_city, Brighton),
        new Fixture(Chelsea, Manchester_city),
        new Fixture(Southampton, Arsenal),
        new Fixture(Newcastle_united, Aston_villa),
        new Fixture(Manchester_United, Sheffield_united),
        new Fixture(Tottenham, West_ham),
        new Fixture(Burnley, Watford),
        new Fixture(Wolvershampton, Bournemouth),
        new Fixture(Liverpool, Crystal_palace)
    ],
    [
        new Fixture(Manchester_city, Liverpool),
        new Fixture(Aston_villa, Wolvershampton),
        new Fixture(Brighton, Manchester_United),
        new Fixture(Arsenal, Norwich_city),
        new Fixture(Crystal_palace, Burnley),
        new Fixture(Watford, Southampton),
        new Fixture(Sheffield_united, Tottenham),
        new Fixture(Bournemouth, Newcastle_united),
        new Fixture(West_ham, Chelsea),
        new Fixture(Everton, Leicester_city)
    ],
    [
        new Fixture(Southampton, Manchester_city),
        new Fixture(Leicester_city, Crystal_palace),
        new Fixture(Wolvershampton, Arsenal),
        new Fixture(Liverpool, Aston_villa),
        new Fixture(Newcastle_united, West_ham),
        new Fixture(Burnley, Sheffield_united),
        new Fixture(Chelsea, Watford),
        new Fixture(Norwich_city, Brighton),
        new Fixture(Tottenham, Everton),
        new Fixture(Manchester_United, Bournemouth)
    ],
    [
        new Fixture(Arsenal, Leicester_city),
        new Fixture(Brighton, Liverpool),
        new Fixture(Sheffield_united, Wolvershampton),
        new Fixture(Everton, Southampton),
        new Fixture(Aston_villa, Manchester_United),
        new Fixture(Manchester_city, Newcastle_united),
        new Fixture(Bournemouth, Tottenham),
        new Fixture(West_ham, Burnley),
        new Fixture(Watford, Norwich_city),
        new Fixture(Crystal_palace, Chelsea)
    ],
    [
        new Fixture(Manchester_United, Southampton),
        new Fixture(Liverpool, Burnley),
        new Fixture(Wolves, Everton),
        new Fixture(Sheffield_united, Chelsea),
        new Fixture(Bournemouth, Leicester_city),
        new Fixture(Brighton, Manchester_city),
        new Fixture(Watford, Newcastle_united),
        new Fixture(Norwich_city, West_ham),
        new Fixture(Tottenham, Arsenal),
        new Fixture(Aston_villa, Crystal_palace)
    ],
    [
        new Fixture(Everton, Aston_villa),
        new Fixture(Chelsea, Norwich_city),
        new Fixture(Southampton, Brighton),
        new Fixture(Burnley, Wolvershampton),
        new Fixture(Manchester_city, Bournemouth),
        new Fixture(Crystal_palace, Manchester_United),
        new Fixture(Leicester_city, Sheffield_united),
        new Fixture(West_ham, Watford),
        new Fixture(Arsenal, Liverpool),
        new Fixture(Newcastle_united, Tottenham)
    ],
    [
        new Fixture(Tottenham, Leicester_city),
        new Fixture(Bournemouth, Southampton),
        new Fixture(Norwich_city, Burnley),
        new Fixture(Aston_villa, Arsenal),
        new Fixture(Wolvershampton, Crystal_palace),
        new Fixture(Manchester_United, West_ham),
        new Fixture(Sheffield_united, Everton),
        new Fixture(Watford, Manchester_city),
        new Fixture(Brighton, Newcastle_united),
        new Fixture(Liverpool, Chelsea)
    ],
    [
        new Fixture(Burnley, Brighton),
        new Fixture(Leicester_city, Manchester_United),
        new Fixture(Chelsea, Wolvershampton),
        new Fixture(Crystal_palace, Tottenham),
        new Fixture(Newcastle_united, Liverpool),
        new Fixture(West_ham, Aston_villa),
        new Fixture(Manchester_city, Norwich_city),
        new Fixture(Arsenal, Watford),
        new Fixture(Southampton, Sheffield_united),
        new Fixture(Everton, Bournemouth)
    ]
];
